package main

import (
	"github.com/mokhtarimokhtar/goasterix"
	"log"
	"testing"
)

func TestAsterixDecoder(t *testing.T) {
	systrackBinaryString :=
		"PgFov1/9CwZ4yAAAABwAIyUjATNk0w2usCUusv5b/JcIT8ExA6CIgMFYoPHLOCAAAAgAAwjJSUzZNQgBL4EBAWB1IP//AUb//PE/AWQQ//8/AP//EEb/EBAE/weWhP8AAMgCXpx4KAT/CE8AAgAO/iAAIAT/BP+E/wT/AL9f/QsGeMgAAAAcACQuyAEyA7QMC/wmafQAXQOHC/OBMQOgiIA7AAAEAAMJC7JMgO0IAPyBAQFgdSD//wEC//zxPwFkAv//AgD//wIC/wICBXgGXYV4AADIAficeCgFeAvzAAIADv4gACAFeAV4hXgFeAC/X/0LBnjIAAAAHAAka1EBMrtNDOOcJrRSADsDqgvhwTEDoFBOTlig9ssoIAAACAABCRrUTK7TBwdjgQEBYHUg//8BBP/w8T8BZAT//wQA//8EBP8EBATXE1uE1wAAyA7GnHgoBNcL4QACAA7+IAAgBNcE14TXBNcAQQAM+HjIAgAAABwN"
	//sysTrackbinaryString2 :=
	//	"PgOtv1/9CwZ4yAAAATv/+WqbAShxaQDK4PN+6AAAAAAP/oEhAYB26ukgIP5ap0ocWgDIgQEBSHEg/xwc//DxPQFAHP//RAD//xz/BLAbcISwAADIAZDUeAbd7H1tBLCoBkABeAYFDv6gJCAEsASwhLAEsAC/X/0LBnjIAAABO//6AS0BJIwA/CNS9DGo//4AAA/7gSEBgHbq7CAA/oBLSSMAALuBAQFIcSD/GRn/8PE9AUAZ//8ZAP//Gf8ExBrzhMQAAMgBdtx4Btv9jOIExA/7qAZAAXgGBQ7+oCQgBMQExITEBMQAv1/9CwZ4yAAAATv/+l04AShjcAC6MvSfBAAE//8P/YEhAYB26uogIP6XTkoY3AdmgQEBSHEg/xwc//DxPQFAHP//HAD//xz/BLAWvYSwAADIDs3JA0LceAbJ7X1lBLAP/agGQAF4BgUO/qAkIASwBLCEsASwAL9f/wsGeMgAAAE7//rHcQEpHesBmPr1HSD/QAOHBv/rKQGOigH5MOJz30gg+iABxgWgIKAwAAAAAAAA/rHcSkd7AQEAYQhUBoYBEQEAdSAcDAyZ//DzfYFB4Az//wwMDAAM/wwM/wwMDAWgFoGFoAAA/4h4yExOSTM3NCAAAACGBEI3MzlNV0lJSVdJREQBQgAbNMgNDckNqtx4A8HqehgFoAb/oAlAAngGB3gDBR//cQIgICAFoAWghaAFoAAAAExOSTM3NCAgICCosUe/X/0LBnjIAAABO//65soBJNdA/H0y9UJU//0AAQ/6gSEBgHbq6yAA/rmzSTXQA0eBAQFIcSD/GRn/8PE9AUAZ//8ZAP//Gf8ExBZShMQAAMgGjtx4BsgXjOEExA/6qAZAAXgGBQ7+oCQgBMQExITEBMQAv1/9CwZ4yAAAATv/+t5yASKd/vnVCPU4XP/7AAMP+4EhAYB26uwgAP63nEingAaJgQEBSHEg/woK//DxPQFACv//CgD//wr/BMQafYTEAADIDRLceAPap5VeBMQP+6gGQAF4AwUO/qAgIATEBMSExATEAL9f/QsGeMgAAAE7//rfpQEm1sn+4FT1Od4Chv2TAV7rOQOuigXEDUW5xxggW8ABwAYYIKAIADAAAAAAAAAB/rfpSbWyBwDxAGEINAZBAQEBAHUgQgsLB//w83+BZeAH//8HCwsAC/8HBwv/BwcLCwsGGBhhhhgAAMgMg8kA7px4KAYYAV6gCUACeAYFeAMFDv4gECAGGAYYhhgGGAA="
	w := new(goasterix.WrapperDataBlock)

	if db, deErr := w.Decode([]byte(systrackBinaryString)); deErr != nil {

		log.Fatalf("Failed to decode %v \n", deErr)
	} else {
		log.Printf("OK %d\n", db)
		for _, aDb := range w.DataBlocks {
			log.Printf("db %v\n", aDb)
		}
	}

}
