serving_port: 8872
#kafka_broker: datalake-kafka-kafka-brokers.datalake-kafka-brokers.svc.cluster.local:9092
kafka_broker: minikube:31063
kafka_topic: public.openatms.systemtrack
hashtags:
  - elonmask
  - bitcoin
consumer:
  replay-mode: true
  replay-type: timestamp
  replay-from: 2022-02-02T09:30:50Z
