# syntax=docker/dockerfile:1
FROM golang:1.18-buster AS builder
WORKDIR /app
COPY go.mod ./
COPY go.sum ./

RUN go mod download


COPY *.go ./


RUN go build -o /kafkist_consumer
# Final Stage - Stage 2
FROM gcr.io/distroless/base-debian10 as baseImage
WORKDIR /app

COPY --from=builder /kafkist_consumer ./kafkist_consumer
COPY config.yaml ./config.yaml
COPY displayer.gotmpl ./displayer.gotmpl
ENV CONFIG_FILE=/app/config.yaml

ENTRYPOINT ["/app/kafkist_consumer"]
EXPOSE 8872

