kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ include "rest-kafka-consumer.fullname" . }}-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Mi
  hostPath:
    path: /Users/putumas/kafkarest
