apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sam-twitter.fullname" . }}
  labels:
    {{- include "sam-twitter.labels" . | nindent 4 }}
data:
  sam-config.yaml: |
    {{- .Values.samConfig | toYaml | nindent 4 }}
