apiVersion: v1
kind: Service
metadata:
  name: {{ include "sam-twitter.fullname" . }}
  labels:
    {{- include "sam-twitter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.samConfig.serving_port }}
      nodePort: {{ .Values.samConfig.nodePort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sam-twitter.selectorLabels" . | nindent 4 }}
